#!/bin/sh

prefix="/opt/macuim"
top=`pwd`
dest="${top}/../../Package/dest"

PATH=/bin:/usr/bin

export MACOSX_DEPLOYMENT_TARGET="11.1"

CPPFLAGS="-no-cpp-precomp" \
CFLAGS="-O3 -DSTDC_HEADERS -std=gnu89 -fstrict-aliasing -funroll-loops -isysroot /Applications/Xcode-12.4.0.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk -arch x86_64 -mmacosx-version-min=11.1" \
LDFLAGS="-arch x86_64" \
./configure --prefix=${prefix} --disable-shared --mandir=${prefix}/share/man \
  --disable-dependency-tracking || exit 1

make -w -j2 || exit 1
