#!/bin/sh

prefix="/opt/macuim"
top=`pwd`
dest="${top}/../../Package/dest"

if [ ! -d ${prefix}/include ]; then
    sudo mkdir ${prefix}/include
fi
if [ ! -d ${prefix}/lib ]; then
    sudo mkdir ${prefix}/lib
fi

PATH="${prefix}/bin:/bin:/bin:/usr/bin"

LIBS="-Wl,-framework -Wl,CoreFoundation -L${prefix}/lib" \
CPPFLAGS="-no-cpp-precomp -isystem ${prefix}/include -D_POLL_EMUL_H_" \
CFLAGS="-Os -std=gnu89 -Wno-deprecated-declarations -funroll-loops -fstrict-aliasing -isysroot /Applications/Xcode-12.4.0.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk -arch x86_64 -mmacosx-version-min=11.1" \
LDFLAGS="-arch x86_64" \
LIBRARY_PATH="${prefix}/lib:/usr/lib" \
./configure --prefix=${prefix} --disable-shared \
  --mandir=${prefix}/share/man --disable-gtk-doc --disable-dependency-tracking \
|| exit 1

LIBS="-L${prefix}/lib" make -w || exit 1
