#!/bin/sh

prefix="/opt/macuim"
top=`pwd`

PATH=/opt/macuim/bin:/bin:/usr/bin
export MACOSX_DEPLOYMENT_TARGET="11.1"

CFLAGS="-isysroot /Applications/Xcode-12.4.0.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk -arch x86_64 -mmacosx-version-min=11.1" \
LDFLAGS="-arch x86_64" \
./configure --prefix=${prefix} --disable-shared \
  --infodir=${prefix}/share/info --mandir=${prefix}/share/man \
  --with-included-gettext --disable-csharp --disable-rpath \
  --disable-dependency-tracking || exit 1

make -w || exit 1
