#!/bin/sh

prefix="/opt/macuim"
top=`pwd`
dest="${top}/../../Package/dest"

export PATH=/opt/macuim/bin:/Library/PRIME/bin:/bin:/usr/bin

export MACOSX_DEPLOYMENT_TARGET="11.1"

PKG_CONFIG="/opt/macuim/bin/pkg-config" \
PKG_CONFIG_PATH="/Library/PRIME/lib/pkgconfig:${prefix}/lib/pkgconfig" \
CFLAGS="-I/Library/PRIME/include -isysroot /Applications/Xcode-12.4.0.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk -arch x86_64 -mmacosx-version-min=11.1" \
LDFLAGS="-L/Library/PRIME/lib" \
LIBS="-Wl,-framework -Wl,CoreFoundation -arch x86_64" \
./configure --prefix=${prefix} --disable-shared \
  --disable-dependency-tracking || exit 1

make -w -j2 || exit 1
